### ISSUE TITLE
delay  rendering

### ISSUE THREAD

**Issue by samantrader** [urbans0ft/fclip#2]
Hi   how can  add  delay  rendering   to  this  code 
that  support     delay rendering  for  file

**Comment by urbans0ft** [comment]
Sorry but I don't know what you mean by "delay rendering". What's the use case, user story you're trying to solve? Perhaps you could provide an example?

**Comment by urbans0ft** [comment]
After some research I assume you mean [1.3.1.4 Delayed Rendering of Clipboard Data](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/fa309d1b-8034-44bf-b927-adfc753e69c1).

> When a copy operation takes place, the actual data associated with the [Clipboard Format (section 1.3.1.2)](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/f293d8e4-7858-4f5f-b00e-8e67323d0538) is not copied onto the remote clipboard. Only the format ID that represents the Clipboard Format is placed on the clipboard. The data associated with the Clipboard Format is sent only if a paste operation is executed.

To my mind this is exactly what happens as the paste operation is handled by the os. `fclip` does **not** copy the file's content to the clipboard! Instead the file's content is only requested by the os when actually performing a paste operation.  
The same behaviour uses `fclip -v` by requesting a file stream from the os instead of extracting the file's content from the clipboard, as--as I mentioned before--the file's content itself is never placed onto the clipboard.
